
services:
  stremio:
    # Uncomment to build the image yourself.
    build:
      context: .
      dockerfile: Dockerfile
    image: th3w1zard1/stremio-server:latest
    container_name: stremio
    hostname: stremio
    networks:
      - proxy
    ports:
      - 8080:8080
      - 11470:11470  # Just one of the two should be enough
      - 12470:12470
    volumes:
      # Mount host ffmpeg if available, otherwise use container's
      #- /bin/ffmpeg:/bin/ffmpeg:ro
      #- /bin/ffprobe:/bin/ffprobe:ro
      # Mount configuration directory as a volume
      - stremio_data:/root/.stremio-server
    environment:
      # Uncomment and set values as needed
      #APP_PATH: /root/.stremio-server/
      #BUILD: linux/arm64
      #CERT_FILE: certificate.pem
      #DISABLE_CACHING: 1
      #DOMAIN: your.custom.domain
      #FFMPEG_EXTRA_OPTS: --enable-libx265
      #JELLYFIN_VERSION: 4.4.1
      #NODE_VERSION: 20
      VERSION: main  # The branch/tag to pull stremio-web from.
      FFMPEG_BIN: /usr/bin
      FFPROBE_BIN: /usr/bin
      ######################################
      # stremio-web related
      # Defaults are configured for running stremio-web in this container.
      CASTING_DISABLED: 1
      NO_CORS: 1
      #IPADDRESS: 127.0.0.1 # Uncomment to use https (not needed when reverse proxy is used)
      # Server and Web UI configuration
      SERVER_URL: http://127.0.0.1:11470/
      # Sets the redirect page for web player and automatically sets up streaming server for you
      # when one tries to access server at port 11470 or 12470.
      # Default is https://app.strem.io/shell-v4.4/
      # When set, the container will download the Web UI from this URL during startup
      # Examples:
      #WEBUI_LOCATION: https://app.strem.io/shell-v4.4/    # Use official release UI
      #WEBUI_LOCATION: http://127.0.0.1:8080/shell/   # Use locally hosted UI
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    driver: bridge

volumes:
  stremio_data:
    name: stremio_data
