# Delete Docker images after PR merge
#

name: 'Clean up Docker images from PR'

on:
  pull_request:
    types: [closed]

jobs:
  purge-image:
    name: Delete image from ghcr.io
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: chipkent/action-cleanup-package@v1.0.1
        with:
          package-name: ${{ github.event.repository.name }}
          tag: ${{ github.head_ref || github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}